version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Core correctness
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

    # Code quality / style
    - revive
    - gocritic
    - whitespace

    # Complexity / maintainability
    - cyclop
    - funlen
    - gocognit

    # Security
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  revive:
    rules:
      - name: var-naming
      - name: line-length-limit
        arguments: [120]
      - name: indent-error-flow
      - name: early-return
      - name: empty-lines

  funlen:
    lines: 80
    statements: 40

  cyclop:
    max-complexity: 15

  gocognit:
    min-complexity: 15

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - cyclop
        - gocognit
    - linters:
        - gosec
      text: "G108:"
